//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MAZE_CELL_TYPE")]
pub struct Model {
    #[sea_orm(column_name = "CELL_TYPE", primary_key, auto_increment = false)]
    pub cell_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::maze_field::Entity")]
    MazeField,
}

impl Related<super::maze_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeField.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
