//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MAZE_FIELD")]
pub struct Model {
    #[sea_orm(column_name = "X", primary_key, auto_increment = false)]
    pub x: u64,
    #[sea_orm(column_name = "Y", primary_key, auto_increment = false)]
    pub y: u64,
    #[sea_orm(column_name = "CELL_TYPE")]
    pub cell_type: String,
    #[sea_orm(column_name = "CELL_OWNER_THREAD_ID")]
    pub cell_owner_thread_id: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maze_cell::Entity",
        from = "(Column::X, Column::Y)",
        to = "(super::maze_cell::Column::X, super::maze_cell::Column::Y)",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCell,
    #[sea_orm(
        belongs_to = "super::maze_cell_type::Entity",
        from = "Column::CellType",
        to = "super::maze_cell_type::Column::CellType",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCellType,
    #[sea_orm(
        belongs_to = "super::therad_list::Entity",
        from = "Column::CellOwnerThreadId",
        to = "super::therad_list::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TheradList,
}

impl Related<super::maze_cell::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCell.def()
    }
}

impl Related<super::maze_cell_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCellType.def()
    }
}

impl Related<super::therad_list::Entity> for Entity {
    fn to() -> RelationDef {
        super::maze_cell::Relation::TheradList.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::maze_cell::Relation::MazeField.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
