//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MAZE_FIELD")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key, auto_increment = false)]
    pub id: u64,
    #[sea_orm(column_name = "CELL_TYPE")]
    pub cell_type: String,
    #[sea_orm(column_name = "CELL_OWNER_THREAD_ID")]
    pub cell_owner_thread_id: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maze_cell::Entity",
        from = "Column::Id",
        to = "super::maze_cell::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCell,
    #[sea_orm(
        belongs_to = "super::maze_cell_type::Entity",
        from = "Column::CellType",
        to = "super::maze_cell_type::Column::CellType",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCellType,
    #[sea_orm(
        belongs_to = "super::thread_list::Entity",
        from = "Column::CellOwnerThreadId",
        to = "super::thread_list::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ThreadList,
}

impl Related<super::maze_cell::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCell.def()
    }
}

impl Related<super::maze_cell_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCellType.def()
    }
}

impl Related<super::thread_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThreadList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
