//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MAZE_CELL_TYPE")]
pub struct Model {
    #[sea_orm(column_name = "CELL_TYPE", primary_key, auto_increment = false)]
    pub cell_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::maze_field::Entity")]
    MazeField,
}

impl Related<super::maze_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeField.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    #[doc = " Create a new ActiveModel with default values. Also used by `Default::default()`."]
    fn new() -> Self {
        <Self as ActiveModelTrait> ::default()
    }

    #[doc = " Will be called before `ActiveModel::insert`, `ActiveModel::update`, and `ActiveModel::save`"]
    #[must_use]
    #[allow(elided_named_lifetimes,clippy::async_yields_async,clippy::diverging_sub_expression,clippy::let_unit_value,clippy::needless_arbitrary_self_type,clippy::no_effect_underscore_binding,clippy::shadow_same,clippy::type_complexity,clippy::type_repetition_in_bounds,clippy::used_underscore_binding)]
    fn before_save<'life0,'async_trait,C, >(self,db: &'life0 C,insert:bool) ->  ::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result<Self,DbErr> > + ::core::marker::Send+'async_trait> >where C:ConnectionTrait,C:'async_trait+ ,'life0:'async_trait,Self: ::core::marker::Send+'async_trait{
        Box::pin(async move {
            if let::core::option::Option::Some(__ret) =  ::core::option::Option::None:: <Result<Self,DbErr> >{
                #[allow(unreachable_code)]
                return __ret;
            }let __self = self;
            let insert = insert;
            let __ret:Result<Self,DbErr>  = {
                Ok(__self)
            };
            #[allow(unreachable_code)]
            __ret
        })
    }

    #[doc = " Will be called after `ActiveModel::insert`, `ActiveModel::update`, and `ActiveModel::save`"]
    #[must_use]
    #[allow(elided_named_lifetimes,clippy::async_yields_async,clippy::diverging_sub_expression,clippy::let_unit_value,clippy::needless_arbitrary_self_type,clippy::no_effect_underscore_binding,clippy::shadow_same,clippy::type_complexity,clippy::type_repetition_in_bounds,clippy::used_underscore_binding)]
    fn after_save<'life0,'async_trait,C, >(model: <Self::Entity as EntityTrait> ::Model,db: &'life0 C,insert:bool,) ->  ::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result< <Self::Entity as EntityTrait> ::Model,DbErr> > + ::core::marker::Send+'async_trait> >where C:ConnectionTrait,C:'async_trait+ ,'life0:'async_trait,Self: ::core::marker::Send+'async_trait{
        Box::pin(async move {
            if let::core::option::Option::Some(__ret) =  ::core::option::Option::None:: <Result< <Self::Entity as EntityTrait> ::Model,DbErr> >{
                #[allow(unreachable_code)]
                return __ret;
            }let model = model;
            let insert = insert;
            let __ret:Result< <Self::Entity as EntityTrait> ::Model,DbErr>  = {
                Ok(model)
            };
            #[allow(unreachable_code)]
            __ret
        })
    }

    #[doc = " Will be called before `ActiveModel::delete`"]
    #[must_use]
    #[allow(elided_named_lifetimes,clippy::async_yields_async,clippy::diverging_sub_expression,clippy::let_unit_value,clippy::needless_arbitrary_self_type,clippy::no_effect_underscore_binding,clippy::shadow_same,clippy::type_complexity,clippy::type_repetition_in_bounds,clippy::used_underscore_binding)]
    fn before_delete<'life0,'async_trait,C, >(self,db: &'life0 C) ->  ::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result<Self,DbErr> > + ::core::marker::Send+'async_trait> >where C:ConnectionTrait,C:'async_trait+ ,'life0:'async_trait,Self: ::core::marker::Send+'async_trait{
        Box::pin(async move {
            if let::core::option::Option::Some(__ret) =  ::core::option::Option::None:: <Result<Self,DbErr> >{
                #[allow(unreachable_code)]
                return __ret;
            }let __self = self;
            let __ret:Result<Self,DbErr>  = {
                Ok(__self)
            };
            #[allow(unreachable_code)]
            __ret
        })
    }

    #[doc = " Will be called after `ActiveModel::delete`"]
    #[must_use]
    #[allow(elided_named_lifetimes,clippy::async_yields_async,clippy::diverging_sub_expression,clippy::let_unit_value,clippy::needless_arbitrary_self_type,clippy::no_effect_underscore_binding,clippy::shadow_same,clippy::type_complexity,clippy::type_repetition_in_bounds,clippy::used_underscore_binding)]
    fn after_delete<'life0,'async_trait,C, >(self,db: &'life0 C) ->  ::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result<Self,DbErr> > + ::core::marker::Send+'async_trait> >where C:ConnectionTrait,C:'async_trait+ ,'life0:'async_trait,Self: ::core::marker::Send+'async_trait{
        Box::pin(async move {
            if let::core::option::Option::Some(__ret) =  ::core::option::Option::None:: <Result<Self,DbErr> >{
                #[allow(unreachable_code)]
                return __ret;
            }let __self = self;
            let __ret:Result<Self,DbErr>  = {
                Ok(__self)
            };
            #[allow(unreachable_code)]
            __ret
        })
    }
}
