//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MAZE_CELL")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u64,
    #[sea_orm(column_name = "X")]
    pub x: u64,
    #[sea_orm(column_name = "Y")]
    pub y: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::maze_field::Entity")]
    MazeField,
    #[sea_orm(has_one = "super::thread_list::Entity")]
    ThreadList,
}

impl Related<super::maze_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeField.def()
    }
}

impl Related<super::thread_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThreadList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
