//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "THERAD_LIST")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key, auto_increment = false)]
    pub id: DateTimeUtc,
    #[sea_orm(column_name = "THREAD_ID")]
    pub thread_id: String,
    #[sea_orm(column_name = "CREATE_UNIXTIME")]
    pub create_unixtime: DateTimeUtc,
    #[sea_orm(column_name = "START_X")]
    pub start_x: u64,
    #[sea_orm(column_name = "START_Y")]
    pub start_y: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maze_cell::Entity",
        from = "(Column::StartX, Column::StartY)",
        to = "(super::maze_cell::Column::X, super::maze_cell::Column::Y)",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCell,
    #[sea_orm(has_many = "super::maze_field::Entity")]
    MazeField,
}

impl Related<super::maze_cell::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCell.def()
    }
}

impl Related<super::maze_field::Entity> for Entity {
    fn to() -> RelationDef {
        super::maze_cell::Relation::MazeField.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::maze_cell::Relation::TheradList.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
