DELETE FROM MAZE_FIELD;
DELETE FROM THREAD_LIST;
DELETE FROM MAZE_CELL;
DELETE FROM MAZE_CELL_TYPE;
DELETE FROM OUTSIDE_WALL_CONNECT_TYPE;
INSERT INTO `MAZE_CELL_TYPE` (`CELL_TYPE`) VALUES ('WALL'), ('PATH'), ('PILLAR');
INSERT INTO OUTSIDE_WALL_CONNECT_TYPE (TYPE) VALUES ('DIRECT_CONNECT'), ('INDIRECT_CONNECT'), ('NOT_CONNECT');
CALL INSERT_NEW_CELL ('0','0','PILLAR');
CALL INSERT_NEW_CELL ('0','1','WALL');
CALL INSERT_NEW_CELL ('0','2','PILLAR');
CALL INSERT_NEW_CELL ('0','3','WALL');
CALL INSERT_NEW_CELL ('0','4','PILLAR');
CALL INSERT_NEW_CELL ('1','0','WALL');
CALL INSERT_NEW_CELL ('1','1','PATH');
CALL INSERT_NEW_CELL ('1','2','PATH');
CALL INSERT_NEW_CELL ('1','3','PATH');
CALL INSERT_NEW_CELL ('1','4','WALL');
CALL INSERT_NEW_CELL ('2','0','PILLAR');
CALL INSERT_NEW_CELL ('2','1','PATH');
CALL INSERT_NEW_CELL ('2','2','PILLAR');
CALL INSERT_NEW_CELL ('2','3','PATH');
CALL INSERT_NEW_CELL ('2','4','PILLAR');
CALL INSERT_NEW_CELL ('3','0','WALL');
CALL INSERT_NEW_CELL ('3','1','PATH');
CALL INSERT_NEW_CELL ('3','2','PATH');
CALL INSERT_NEW_CELL ('3','3','PATH');
CALL INSERT_NEW_CELL ('3','4','WALL');
CALL INSERT_NEW_CELL ('4','0','PILLAR');
CALL INSERT_NEW_CELL ('4','1','WALL');
CALL INSERT_NEW_CELL ('4','2','PILLAR');
CALL INSERT_NEW_CELL ('4','3','WALL');
CALL INSERT_NEW_CELL ('4','4','PILLAR');



