DELETE FROM MAZE_FIELD;
DELETE FROM THREAD_LIST;
DELETE FROM MAZE_CELL;
DELETE FROM MAZE_CELL_TYPE;
DELETE FROM OUTSIDE_WALL_CONNECT_TYPE;
INSERT INTO `MAZE_CELL_TYPE` (`CELL_TYPE`) VALUES ('WALL'), ('PATH'), ('PILLAR');
INSERT INTO OUTSIDE_WALL_CONNECT_TYPE (TYPE) VALUES ('DIRECT_CONNECT'), ('INDIRECT_CONNECT'), ('NOT_CONNECT');
CALL INSERT_NEW_CELL ('0','0','PILLAR');
CALL INSERT_NEW_CELL ('0','1','WALL');
CALL INSERT_NEW_CELL ('0','2','PILLAR');
CALL INSERT_NEW_CELL ('0','3','WALL');
CALL INSERT_NEW_CELL ('0','4','PILLAR');
CALL INSERT_NEW_CELL ('0','5','WALL');
CALL INSERT_NEW_CELL ('0','6','PILLAR');
CALL INSERT_NEW_CELL ('1','0','WALL');
CALL INSERT_NEW_CELL ('1','1','PATH');
CALL INSERT_NEW_CELL ('1','2','PATH');
CALL INSERT_NEW_CELL ('1','3','PATH');
CALL INSERT_NEW_CELL ('1','4','PATH');
CALL INSERT_NEW_CELL ('1','5','PATH');
CALL INSERT_NEW_CELL ('1','6','WALL');
CALL INSERT_NEW_CELL ('2','0','PILLAR');
CALL INSERT_NEW_CELL ('2','1','PATH');
CALL INSERT_NEW_CELL ('2','2','PILLAR');
CALL INSERT_NEW_CELL ('2','3','PATH');
CALL INSERT_NEW_CELL ('2','4','PILLAR');
CALL INSERT_NEW_CELL ('2','5','PATH');
CALL INSERT_NEW_CELL ('2','6','PILLAR');
CALL INSERT_NEW_CELL ('3','0','WALL');
CALL INSERT_NEW_CELL ('3','1','PATH');
CALL INSERT_NEW_CELL ('3','2','PATH');
CALL INSERT_NEW_CELL ('3','3','PATH');
CALL INSERT_NEW_CELL ('3','4','PATH');
CALL INSERT_NEW_CELL ('3','5','PATH');
CALL INSERT_NEW_CELL ('3','6','WALL');
CALL INSERT_NEW_CELL ('4','0','PILLAR');
CALL INSERT_NEW_CELL ('4','1','PATH');
CALL INSERT_NEW_CELL ('4','2','PILLAR');
CALL INSERT_NEW_CELL ('4','3','PATH');
CALL INSERT_NEW_CELL ('4','4','PILLAR');
CALL INSERT_NEW_CELL ('4','5','PATH');
CALL INSERT_NEW_CELL ('4','6','PILLAR');
CALL INSERT_NEW_CELL ('5','0','WALL');
CALL INSERT_NEW_CELL ('5','1','PATH');
CALL INSERT_NEW_CELL ('5','2','PATH');
CALL INSERT_NEW_CELL ('5','3','PATH');
CALL INSERT_NEW_CELL ('5','4','PATH');
CALL INSERT_NEW_CELL ('5','5','PATH');
CALL INSERT_NEW_CELL ('5','6','WALL');
CALL INSERT_NEW_CELL ('6','0','PILLAR');
CALL INSERT_NEW_CELL ('6','1','WALL');
CALL INSERT_NEW_CELL ('6','2','PILLAR');
CALL INSERT_NEW_CELL ('6','3','WALL');
CALL INSERT_NEW_CELL ('6','4','PILLAR');
CALL INSERT_NEW_CELL ('6','5','WALL');
CALL INSERT_NEW_CELL ('6','6','PILLAR');


CALL ADD_NEW_THREAD ('2','4','AAA','1234567890');
CALL PATH_TO_WALL ('2','5','AAA','1234567890');
SELECT * FROM USED_START_POINTS_VIEW;
-- UPDATED_OUTSIDEが返ってくる。
CALL GET_START_POINT_FROM_UNUSED_START_POINTS ('2', '6', 'AAA', '1234567890');
SELECT * FROM USED_START_POINTS_VIEW;

CALL ADD_NEW_THREAD ('4','2','BBB','1234567890');
CALL PATH_TO_WALL ('4','3','BBB','1234567890');
SELECT * FROM USED_START_POINTS_VIEW;
-- UPDATEDが返ってくる。
CALL GET_START_POINT_FROM_UNUSED_START_POINTS ('4', '4', 'BBB','1234567890');
SELECT * FROM USED_START_POINTS_VIEW;


-- これは上２つと同時にはできない。
CALL ADD_NEW_THREAD ('2','0','CCC','1234567890');
CALL PATH_TO_WALL ('2','1','CCC','1234567890');
SELECT * FROM USED_START_POINTS_VIEW;
-- UPDATEDが返ってくる?
CALL GET_START_POINT_FROM_UNUSED_START_POINTS ('2', '2', 'CCC','1234567890');
SELECT * FROM USED_START_POINTS_VIEW;




-- エラーが返ってくる。 
CALL GET_START_POINT_FROM_UNUSED_START_POINTS ('6', '2', 'AAA', '1234567890'); 



