//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "OUTSIDE_WALL_CONNECT_TYPE")]
pub struct Model {
    #[sea_orm(column_name = "TYPE", primary_key, auto_increment = false)]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::thread_list::Entity")]
    ThreadList,
}

impl Related<super::thread_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ThreadList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
