//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "THREAD_LIST")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: u64,
    #[sea_orm(column_name = "THREAD_ID")]
    pub thread_id: String,
    #[sea_orm(column_name = "CREATE_UNIXTIME")]
    pub create_unixtime: i64,
    #[sea_orm(column_name = "START_CELL", unique)]
    pub start_cell: u64,
    #[sea_orm(column_name = "OUTSIDE_WALL_CONNECT_TYPE")]
    pub outside_wall_connect_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maze_cell::Entity",
        from = "Column::StartCell",
        to = "super::maze_cell::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    MazeCell,
    #[sea_orm(has_many = "super::maze_field::Entity")]
    MazeField,
    #[sea_orm(
        belongs_to = "super::outside_wall_connect_type::Entity",
        from = "Column::OutsideWallConnectType",
        to = "super::outside_wall_connect_type::Column::Type",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    OutsideWallConnectType,
}

impl Related<super::maze_cell::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeCell.def()
    }
}

impl Related<super::maze_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MazeField.def()
    }
}

impl Related<super::outside_wall_connect_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutsideWallConnectType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
